spring:
  application:
    name: SemanticSearchEngine

  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://openrouter.ai/api

      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine_distance
        max-document-batch-size: 100

logging:
  level:
    org.springframework.ai: DEBUG